---
WORDPRESS_DB_HOST: "db"
WORDPRESS_DB_USER: "dmitry"
WORDPRESS_DB_PASSWORD: "12345678"
WORDPRESS_DB_NAME: "dmitrydb"
MYSQL_DATABASE: "dmitrydb"
MYSQL_USER: "dmitry"
MYSQL_PASSWORD: "12345678"
PROJECT_NAME: "phoenix"
PROJECT_DIR: "/home/{{ PROJECT_NAME }}"