- name: Install Zabbex agent
  hosts: all
  become: yes

  tasks:
    - name: Command in shell
      ansible.builtin.shell: |
        wget https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.0-1+ubuntu20.04_all.deb
        dpkg -i zabbix-release_6.0-1+ubuntu20.04_all.deb
        apt update

    - name: Install agent
      apt: 
        pkg:
         - zabbix-agent
        state: latest
        update_cache: yes

    - name: Command in shell
      ansible.builtin.shell: |
        systemctl restart zabbix-agent
        systemctl enable zabbix-agent 

